import type { Locale } from "./locale";

/** Non-CMS UI bits (filters, empty states, aria). */
export function ui(locale: Locale) {
  if (locale === "ar") {
    return {
      portfolioFilterAll: "الكل",
      portfolioEmpty: "لا توجد عناصر منشورة في هذا الاختيار من المعارض.",
      video: "فيديو",
      languageEn: "English",
      languageAr: "العربية",
      navJournal: "المجلة",
      navAiStudio: "استوديو AI",
      navBook: "الحجز",
      homeCtaAiStudio: "استكشف استوديو AI",
      homeCtaBook: "احجز جلسة",
      footerJournal: "المجلة",
      footerAiStudio: "استوديو AI",
      footerBooking: "الحجز",
      footerPrivacy: "الخصوصية",
      footerTerms: "الشروط",
      legalPrivacyKicker: "الخصوصية",
      legalTermsKicker: "الشروط",
      journalTitle: "المجلة",
      journalEmpty: "لا توجد مقالات منشورة بعد.",
      journalReadMore: "اقرأ المقال",
      journalBreadcrumb: "المجلة",
      journalBackToIndex: "كل المقالات",
      journalCtaNote: "للاستفسار عن مشروع تصوير أو فيلم،",
      journalCtaLink: "تواصل معنا",
      serviceBookThis: "احجز هذه الخدمة",
      bookSelectedService: "الخدمة المختارة",
      serviceViewDetails: "عرض الخدمة",
      serviceCoverPlaceholder: "صورة الغلاف تُعرَف من لوحة الإدارة",
      serviceBreadcrumbParent: "الخدمات",
      serviceBackToAll: "كل الخدمات",
      serviceGalleryHeading: "معرض الصور",
      serviceProcessHeading: "آلية العمل والتسليم",
      serviceFaqHeading: "أسئلة شائعة",
    };
  }
  return {
    portfolioFilterAll: "All",
    portfolioEmpty: "No published items in this gallery selection.",
    video: "Video",
    languageEn: "English",
    languageAr: "Arabic",
    navJournal: "Journal",
    navAiStudio: "AI Studio",
    navBook: "Book",
    homeCtaAiStudio: "Explore AI Studio",
    homeCtaBook: "Book a session",
    footerJournal: "Journal",
    footerAiStudio: "AI Studio",
    footerBooking: "Booking",
    footerPrivacy: "Privacy",
    footerTerms: "Terms",
    legalPrivacyKicker: "Privacy",
    legalTermsKicker: "Terms",
    journalTitle: "Journal",
    journalEmpty: "No published articles yet.",
    journalReadMore: "Read article",
    journalBreadcrumb: "Journal",
    journalBackToIndex: "All articles",
    journalCtaNote: "To discuss a photography or film commission,",
    journalCtaLink: "contact the studio",
    serviceBookThis: "Book this service",
    bookSelectedService: "Selected service",
    serviceViewDetails: "View service",
    serviceCoverPlaceholder: "Cover image is set in Admin",
    serviceBreadcrumbParent: "Services",
    serviceBackToAll: "All services",
    serviceGalleryHeading: "Gallery",
    serviceProcessHeading: "Process & deliverables",
    serviceFaqHeading: "Frequently asked questions",
  };
}
